### PR TITLE
Refactor Post and User models

### PR DESCRIPTION
**Pull request by 0vai5**
- Added user field to the Post model to store the reference to the user who created the post.
- Updated the User model to include an array of Post references.
- Updated the post.ejs view to display the author's username.
- Updated the profile.ejs view to display the user's posts.
- Updated the admin.ejs layout to remove the script tag for the script.js file.
- Updated the header.ejs and header_admin.ejs partials to remove the class attribute from the anchor tags.
- Updated the style.css file to add styles for the submitBtn class.
- Added the user.png image to the public/img directory.
- Created the manage-users.ejs view for managing users in the admin panel.
- Updated the main.js route file to populate the user field when fetching a post by its ID.
- Updated the package.json file to add dev dependencies for bcrypt and jsonwebtoken.

### CODE REVIEW

**Comment by 0vai5** [comment]
@jinx-vi-0 Merge the pull request as your tests are completed and if there are any issues please reassign to me

**Comment by adarsh-site** [comment]
> @jinx-vi-0 Merge the pull request as your tests are completed and if there are any issues please reassign to me

There is a syntax error in admin.js. Please test your changes before submitting a PR and also resolve the conflict.

**Comment by 0vai5** [comment]
It looks like everything’s fixed now! The issue came from the last merge we did. 😊
@jinx-vi-0

**Comment by 0vai5** [comment]
Please label it as a level.
@jinx-vi-0

**Pull request merged**
