### PR TITLE
Added dark mode toggle, button design changes, and adjusted layout

### PR DESCRIPTION
**Pull request by AnsharaFayazBeigh**
@jinx-vi-0 
Issue #26
This pull request introduces a dark mode feature, along with some design and layout enhancements. 

1. Dark Mode Toggle: Implemented a button that allows users to switch between light and dark mode.

2. Adjusted CSS to ensure the dark mode complements the existing design, with changes to the background and text colors.
3. Ensure all elements, including the header, links, and text, adapt properly to dark mode.
Button Styling: Updated the styling of the toggle button to match the overall design:
The font was updated to match the rest of the website (Poppins).
Added smooth transition effects for hover states.
Improved the button’s appearance by adjusting padding, border radius, and colors.
Layout Adjustments: Tweaked the layout in style.css to enhance user experience.
Minor changes to spacing and alignment of elements
Testing: Tested the changes locally, and everything works as expected in both light and dark modes.
No major visual or functional regressions were encountered.
After Dark mode implementation : 
image

### CODE REVIEW

**Comment by AnsharaFayazBeigh** [comment]
Also about the merge conflicts ( i checked my code editor and tried to fetch) : 

image how

ever it doesn't show any but the merge conflicts are present in the pull request.. 

@jinx-vi-0

**Review by adarsh-site — CHANGES_REQUESTED** [review]
1. If I'm enabling dark mode, it should reflect on all the pages.
2. Fetch latest changes from the main branch.
3. Fix merge confict.

**Review by AnsharaFayazBeigh — COMMENTED** [review]
I have updated the required file to make the dark mode consistent. 
And reviewed the merge conflicts.. as much as I can manually.

**Comment by AnsharaFayazBeigh** [comment]
@jinx-vi-0 I have incorporated the feature to make the changes uniform ( making the dark-mode uniform). There was a typo with the search bar (it was search). Please review it. Thank you!

**Review by adarsh-site — APPROVED** [review]

**Pull request merged**
